config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :addresses, only: %i(index create)
  match '/my_address', to: 'addresses#index', via: [:get]

  get 'pages/home'
  root to: "addresses#index"
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user, optional: true
  validates_uniqueness_of :user_id, allow_nil: true, allow_blank: true
  before_create :set_address_value

  private

  # Assign address value
  # @note run as callback from before_create
  # @return [String]
  # @see Address.generate_address
  def set_address_value
    self.address = generate_address
  end

  # Prepare address value
  # @return [String]
  # @see Address.set_address_value
  def generate_address
    arr = [('a'..'z'), ('A'..'Z'), (0..9)].map(&:to_a).flatten
    filtered = arr.reject { |x| ['O', 0, 'I', 'i'].include?(x) }
    (0...34).map { filtered[rand(filtered.length)] }.join
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :rememberable, :validatable

  has_one :address
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :authenticate_user!

  respond_to :json
  # GET /addresses
  # GET /addresses.json
  def index
    respond_with @address = current_user.address
  end

  # POST /addresses.json
  def create
    build_address
  end

  private

  # Call AddressService for build address for user
  # @see AddressService
  def build_address
    status, result = AddressService.new(current_user.id).build_address
    send_response(status, result)
  end

  # Render response for #create
  # @return [Hash]
  # @example Response
  #    {
  #     address: {
  #       address: 'smcWD32832UF2I23J928DFJ92' # OR null
  #     },
  #     message: 'message'
  #   }
  # @see AddressesController.build_address
  def send_response(status, result)
    address = Address.find_by_user_id current_user.id
    if status
      render json: { address: address, message: result }, status: 200
    else
      render json: { address: address, message: result }, status: 422
    end
  end
end

app/controllers/application_controller.rb
require 'application_responder'

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  protect_from_forgery with: :exception
  prepend_view_path Rails.root.join('frontend')

  before_action :gon_address, unless: :devise_controller?

  private

  def after_sign_in_path_for(_resource)
    my_address_path
  end

  def gon_address
    gon.address = if current_user && !current_user.address.nil?
                    current_user.address.address
                  else
                    0
                  end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Render flash massage  vis js
  def render_flash
    javascript_tag('App.flash = JSON.parse(' "'#{j({ success: flash.notice, error: flash.alert }.to_json)}'" ');')
  end

  # Render partial helper
  # @param partial name
  # @example
  #   component('my_partial')
  # @return rendered partials components/my/_partial
  def component(component_name, locals = {}, &block)
    name = component_name.split('_').first
    render("components/#{name}/#{component_name}", locals, &block)
  end

  # Render partial helper with controller name in path
  # @param partial name
  # @example
  #   controller_component('my_partial')
  # @return rendered partials components/controller_name/_partial
  def controller_component(component_name, locals = {}, &block)
    render("components/#{controller_name}/#{component_name}", locals, &block)
  end

  alias c component
  alias c_c component
end

app/views/addresses/index.html.erb
<div class="container">
  <h1>Addresses</h1>
  <hr>
  <h2>My Address</h2>
  <div id="address">
    <%=	 current_user.address&.address %>
  </div>
  <%=	link_to t('generate_address'), addresses_path, method: :post, remote: true, class: 'btn btn-primary', format: :json , id: 'refresh_address_btn',
               data: { token: form_authenticity_token} %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="<%= I18n.locale %>">
  <head>
    <%= csrf_meta_tags %>
    <title>Cources</title>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= Gon::Base.render_data %>
    <%= stylesheet_pack_tag 'bootstrap/bootstrap', media: 'all' %>
    <%= stylesheet_pack_tag 'vendor', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'turbolinks'%>
  </head>
  <body>
    <%= yield %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-eval': false %>
    <%=	render_flash %>
  </body>
</html>